USE [DEV_ACADEMY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_CHECK_STUDENT_IN_INVOICE]
    @StudentID VARCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1 FROM INVOICE 
        WHERE StudentID = @StudentID 
          AND (DELETE_FLG IS NULL OR DELETE_FLG = 0)
    )
        SELECT 1 AS [Exists];
    ELSE
        SELECT 0 AS [Exists];
END
GO