SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [SP_GET_COURSES_BY_STUDENT]
    @StudentID VARCHAR(10)
AS
BEGIN
	SELECT DISTINCT
		CO.course_id,
		CO.course_name,
		SU.SubjectID,
		SU.SubjectName
	FROM CLASS_ENROLLMENT CE
	JOIN CLASS CL ON CE.ClassID = CL.ClassID
	JOIN Course CO ON CO.course_id = CL.course_id
	JOIN SEMESTER SE ON SE.course_id = CO.course_id
	JOIN SUBJECT SU ON SE.SemesterID = SU.SemesterID
	WHERE StudentID = @StudentID
		AND is_active = 1
END


