USE [DEV_ACADEMY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [SP_GET_SUBJECT_ENDTIME]
    @ClassID UNIQUEIDENTIFIER,
    @SubjectID VARCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MAX(StartTime) AS EndTime
    FROM CLASS_SCHEDULE
    WHERE ClassID = @ClassID AND SubjectID = @SubjectID;
END


