
CREATE Or ALTER PROCEDURE SP_INFOR_STUDENT_PRINT_EMAIL
	@ClassID UNIQUEIDENTIFIER 
AS
BEGIN
	

    -- Insert statements for procedure here
	SELECT S.FullName, S.Email
	FROM STUDENT S
		INNER JOIN CLASS_ENROLLMENT CE ON CE.StudentID = S.StudentID
		INNER JOIN CLASS C ON C.ClassID = CE.ClassID
	WHERE CE.ClassID = @ClassID
END
GO

--EXEC SP_INFOR_STUDENT_PRINT_EMAIL 'F8616B8A-6F52-4FAD-8758-0C2784D0D877'

--SELECT * FROM CLASS_ENROLLMENT