USE [DEV_ACADEMY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_INSERT_SUBJECT]
    @SubjectID VARCHAR(10),
    @SubjectName NVARCHAR(100),
    @SemesterID VARCHAR(10),
    @TuitionFee DECIMAL(12,2)
AS
BEGIN
    --SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        INSERT INTO SUBJECT (SubjectID, SubjectName, SemesterID, TuitionFee, DELETE_FLG)
        VALUES (@SubjectID, @SubjectName, @SemesterID, @TuitionFee, 0);

        COMMIT TRANSACTION;
        RETURN 1;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        DECLARE @Err NVARCHAR(4000) = ERROR_MESSAGE();
        RAISERROR(@Err, 16, 1);
        RETURN 0;
    END CATCH
END
